# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8b7f2a5f550266455df226caf071faf3763d28c80c72ffe876d51a73e53e74de88f4c2c1211dfe617f950ac8d94c9abd15aaac1ca158822d946ccb303cc99d1

test:
  secret_key_base: a560de28936f502ff0a43c457300c11c36de538566db6e6ffb01ad8f03b1fad965cfa533ed38b3e74122485afa367999a9028bfb4c35bf1294653152082f7473

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
